### ISSUE TITLE
TypeError: 'Command' object is not iterable

### ISSUE THREAD

**Issue by avrogachev** [prostomarkeloff/vk.py#11]
I tried to test the examples and got the following error:

DEBUG:vk.bot_framework.dispatcher.rule:Rule Commands succesfully called!
ERROR:vk.bot_framework.dispatcher.dispatcher:Error in handler (get_admin_rights):
Traceback (most recent call last):
  File "/home/alexander/anaconda3/lib/python3.7/site-packages/vk/bot_framework/dispatcher/dispatcher.py", line 240, in _process_event
    ev.object, data
  File "/home/alexander/anaconda3/lib/python3.7/site-packages/vk/bot_framework/dispatcher/handler.py", line 42, in execute_handler
    result = await rule(*args)
  File "/home/alexander/anaconda3/lib/python3.7/site-packages/vk/bot_framework/dispatcher/rule.py", line 23, in __call__
    return await self.check(event, data)
  File "/home/alexander/anaconda3/lib/python3.7/site-packages/vk/bot_framework/rules/rules.py", line 54, in check
    for commands in self.commands:
TypeError: 'Command' object is not iterable

it is about simple_rule.py and any commands

**Comment by prostomarkeloff** [comment]
Hello, you download library from pip?

**Comment by prostomarkeloff** [comment]
Now I tested code from example in lastest version (pip install https://github.com/prostomarkeloff/vk.py/archive/master.zip --upgrade) - all works.

**Comment by prostomarkeloff** [comment]
Fixed now. Please update from github (pip install https://github.com/prostomarkeloff/vk.py/archive/master.zip --upgrade)

**Comment by avrogachev** [comment]
Thanks a lot!!! Now everything is good!
