### ISSUE TITLE
ValueError: 'message_typing_state' is not a valid Event

### ISSUE THREAD

**Issue by Xokare** [prostomarkeloff/vk.py#39]
# Your problem
При наборе сообщения возвращает ошибку ValueError: 'message_typing_state' is not a valid Event

```
INFO:root:Task run successfully added!
INFO:root:Loop started!
INFO:vk.bot_framework.extensions.polling:Polling started!
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Dispatcher._process_event() done, defined at C:\Users\Nikit\AppData\Local\Programs\Python\Python38\lib\site-packages\vk\bot_framework\dispatcher\dispatcher.py:132> exception=ValueError("'message_typing_state' is not a valid Event")>
ValueError: 'message_typing_state' is not a valid Event

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nikit\AppData\Local\Programs\Python\Python38\lib\site-packages\vk\bot_framework\dispatcher\dispatcher.py", line 149, in _process_event
    ev = await get_event_object(event)  # get event pydantic model.
  File "C:\Users\Nikit\AppData\Local\Programs\Python\Python38\lib\site-packages\vk\utils\get_event.py", line 6, in get_event_object
    _event_type = Event(event["type"])
  File "C:\Users\Nikit\AppData\Local\Programs\Python\Python38\lib\enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\Nikit\AppData\Local\Programs\Python\Python38\lib\enum.py", line 595, in __new__
    raise exc
  File "C:\Users\Nikit\AppData\Local\Programs\Python\Python38\lib\enum.py", line 579, in __new__
    result = cls._missing_(value)
  File "C:\Users\Nikit\AppData\Local\Programs\Python\Python38\lib\enum.py", line 608, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'message_typing_state' is not a valid Event


```

# Code

```
from vk import VK
from vk.utils import TaskManager
from vk.bot_framework import Dispatcher
from vk import types

import logging

logging.basicConfig(level="INFO")

bot_token = 'token'
vk = VK(bot_token)
gid = 123
task_manager = TaskManager(vk.loop)
api = vk.get_api()

dp = Dispatcher(vk, gid)

@dp.message_handler(text="test")
async def handle_event(message: types.Message, data: dict):
    await message.reply("принял")


async def run():
    await dp.run_polling()


if __name__ == "__main__":
    task_manager.add_task(run)
    task_manager.run(auto_reload=True)
```

# Steps to reproduce
Поправить список valid Event

# Environment
VK.py version: (0.5.0)

Python version: 3.8.0

OS: Microsoft Windows [Version 10.0.18950.1000]

**Comment by prostomarkeloff** [comment]
Данное событие не указано в [документации](https://vk.com/dev/groups_events). Рекомендую его отключить, но если Вы всё же хотите чтобы оно было -- узнайте как оно выглядит, и сделайте PR.

**Comment by Xokare** [comment]
Вк не перестаёт удивлять, но ладно. Событие лично мне не нужно, поэтому снял галку "Статус набора текста" в настройках Long Poll и оно исчезло, но по хорошему что-то с ним надо делать
